apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpcli
  template:
    metadata:
      labels:
        app: wpcli
    spec:
      containers:
      - name: wpcli
        image: wordpress:cli-php8.1
        # Use same www-data user and group as the wordpress container
        securityContext:
          runAsUser: 33
          runAsGroup: 33
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/www/html
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-wp:3306
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-user-password-9m7k5b4k2m
                key: passworduser
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-user-4t5mcf8dkm
                key: username
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-database-4f74mgddt5
                key: database
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim

